device_type:
  manufacturer: v-zug
  model: Adora S
  icon: mdi-dishwasher
  nominal_power: 100
  nominal_duration: 7200
  constant: true
  state:
    state_on:
      threshold: 10
    state_off:
      threshold: 1
      upper: 20
      lower: 15
      for: 1500
      trailing_zeros_for: 720
