device_type:
  manufacturer: v-zug
  model: Adora TS WP
  icon: mdi-tumble-dryer
  nominal_power: 800
  nominal_duration: 7200
  constant: true
  state:
    state_on:
      threshold: 10
    state_off:
      threshold: 1
      upper: 0
      lower: 0
      for: 0
      trailing_zeros_for: 10
